# -*- coding: utf-8 -*-
"""Retail_Data_Engineering_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckWDNtns5XXllR2nNRQd5gUyr96fHOkM
"""



"""Retail Sales Data Processing and Business Insights Generation

Company: ABC Retail Solutions

Objective:
Build an end-to-end data engineering pipeline to ingest,
clean, transform, validate, secure, and analyze retail
sales data for business intelligence reporting.
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

file_path = "USECASE - Data Engineering.xlsx"

product_df = pd.read_excel(
    file_path,
    sheet_name="PRODUCT DETAILS",
    header=3
)

retail1 = pd.read_excel(
    file_path,
    sheet_name="RETAIL DATA 1",
    header=2
)

retail2 = pd.read_excel(
    file_path,
    sheet_name="RETAIL DATA 2",
    header=4
)

product_df.head()

retail1.head()

retail2.head()

print("Product Details Shape:", product_df.shape)
print("Retail Data 1 Shape:", retail1.shape)
print("Retail Data 2 Shape:", retail2.shape)

print(product_df.columns)
print(retail1.columns)
print(retail2.columns)

retail1.info()

retail2.info()

retail2.isnull().sum()

retail1.isnull().sum()

print(retail1.duplicated().sum())
print(retail2.duplicated().sum())

"""Data Quality Assessment

Findings:

1. Missing values identified in Price column.
2. transaction_date stored as object datatype.
3. Email and phone contain PII information.
4. Duplicate records need validation.
5. Product and category standardization required.
"""

print("Retail1 Missing Values")
print(retail1.isnull().sum())

print("\nRetail2 Missing Values")
print(retail2.isnull().sum())

print("\nRetail1 Duplicates")
print(retail1.duplicated().sum())

print("\nRetail2 Duplicates")
print(retail2.duplicated().sum())

"""Data Quality Assessment Results

1. Retail Data 1 contains 404 missing price values.
2. Retail Data 2 contains 405 missing price values.
3. No duplicate records were identified in either dataset.
4. transaction_date is stored as object datatype and requires conversion.
5. Email and phone columns contain PII information and require masking.
6. Product and category standardization will be performed.
"""

retail_df = pd.concat(
    [retail1, retail2],
    ignore_index=True
)

ignore_index=True

print(retail_df.shape)

print(retail_df.shape)
retail_df.head()

product_df.head()

product_df.columns

print("Missing Prices Before:")
print(retail_df["price"].isnull().sum())

price_lookup = product_df.set_index("product_id")["price"]

retail_df["price"] = retail_df["price"].fillna(
    retail_df["product_id"].map(price_lookup)
)

print("Missing Prices After:")
print(retail_df["price"].isnull().sum())

"""Missing Price Treatment

Problem:
809 records contained missing prices.

Solution:
A product price lookup table was created using the Product Details reference dataset. Missing prices were imputed using the corresponding product_id.

Reason:
This ensured accurate revenue calculations and maintained consistency with the organization's master product data.
"""

print("Missing Prices Before:")
print(retail_df["price"].isnull().sum())

price_lookup = product_df.set_index("product_id")["price"]

retail_df["price"] = retail_df["price"].fillna(
    retail_df["product_id"].map(price_lookup)
)

print("Missing Prices After:")
print(retail_df["price"].isnull().sum())

print(retail_df["category"].unique())

category_mapping = {
    "ELEC": "Electronics",
    "electronics": "Electronics",

    "CLOTH": "Clothing",
    "clothing": "Clothing",

    "FURN": "Furniture",
    "furniture": "Furniture",

    "home appliances": "Home Appliances",
    "HOME": "Home Appliances"
}

retail_df["category"] = retail_df["category"].replace(category_mapping)

print(retail_df["category"].unique())

"""Category Standardization

Problem:
The category column contained multiple representations of the same business category, such as ELEC, electronics, Electronics, FURN, furniture, and HOME.

Solution:
A category mapping dictionary was created and applied using Pandas replace() to standardize category values.

Reason:
This ensured accurate aggregation and reporting in Power BI by preventing duplicate business categories.
"""

print(retail_df["category"].unique())

print(retail_df["product_name"].unique())

retail_df["product_name"] = retail_df["product_name"].str.strip().str.title()

print(retail_df["product_name"].unique())

"""Product Name Standardization

Problem:
Product names were stored in different formats across source systems.

Solution:
Whitespace was removed using strip() and product names were converted to title case using title().

Reason:
This ensured consistent product representation and accurate product-level reporting.
"""

print(retail_df["transaction_date"].dtype)

retail_df["transaction_date"] = pd.to_datetime(
    retail_df["transaction_date"],
    errors="coerce"
)

print(retail_df["transaction_date"].dtype)

print(
    retail_df["transaction_date"].isnull().sum()
)

"""Date Standardization

Problem:
transaction_date was stored as object datatype.

Solution:
The column was converted to datetime using Pandas to_datetime() function.

Reason:
This enables time-based analysis, trend reporting, and Power BI date intelligence features.
"""

print(retail_df["transaction_date"].dtype)

retail_df["transaction_date"] = pd.to_datetime(
    retail_df["transaction_date"],
    errors="coerce"
)

print(retail_df["transaction_date"].dtype)

print(retail_df["transaction_date"].isnull().sum())

retail_df[["email","phone"]].head()

def mask_email(email):
    if pd.isnull(email):
        return email

    name, domain = email.split("@")
    return name[:2] + "***@" + domain

retail_df["email"] = retail_df["email"].apply(mask_email)

def mask_phone(phone):
    phone = str(phone)

    return phone[:2] + "******" + phone[-2:]

retail_df["phone"] = retail_df["phone"].apply(mask_phone)

retail_df[["email","phone"]].head()

"""PII Masking

Problem:
Customer email addresses and phone numbers contain personally identifiable information (PII).

Solution:
Email addresses and phone numbers were masked using custom Python functions.

Reason:
This protects sensitive customer information and ensures compliance with data governance and privacy requirements.
"""

retail_df["revenue"] = (
    retail_df["price"]
    * retail_df["quantity"]
    * (1 - retail_df["discount"])
)

retail_df[
    ["price", "quantity", "discount", "revenue"]
].head()

total_revenue = retail_df["revenue"].sum()

print("Total Revenue:", total_revenue)

revenue_by_category = retail_df.groupby(
    "category"
)["revenue"].sum()

print(revenue_by_category)

revenue_by_city = retail_df.groupby(
    "city"
)["revenue"].sum()

print(revenue_by_city)

total_orders = retail_df["transaction_id"].nunique()

print("Total Orders:", total_orders)

total_customers = retail_df["customer_id"].nunique()

print("Total Customers:", total_customers)

avg_order_value = total_revenue / total_orders

print("Average Order Value:", avg_order_value)

"""KPI Calculation

Revenue was calculated using:

Revenue = Price × Quantity × (1 - Discount)

The following KPIs were generated:

1. Total Revenue
2. Revenue by Category
3. Revenue by City
4. Total Orders
5. Total Customers
6. Average Order Value

These KPIs provide insights into business performance, customer activity, and regional sales trends.
"""

retail_df.to_csv(
    "cleaned_retail_data.csv",
    index=False
)

retail_df["revenue"] = (
    retail_df["price"]
    * retail_df["quantity"]
    * (1 - retail_df["discount"])
)

total_revenue = retail_df["revenue"].sum()

print(total_revenue)

revenue_by_category = retail_df.groupby("category")["revenue"].sum()

print(revenue_by_category)

revenue_by_city = retail_df.groupby("city")["revenue"].sum()

print(revenue_by_city)

total_orders = retail_df["transaction_id"].nunique()

total_customers = retail_df["customer_id"].nunique()

avg_order_value = total_revenue / total_orders

print("Total Orders:", total_orders)

print("Total Customers:", total_customers)

print("Average Order Value:", avg_order_value)

top_products = retail_df.groupby(
    "product_name"
)["revenue"].sum().sort_values(
    ascending=False
)

print(top_products)

payment_analysis = retail_df.groupby(
    "payment_method"
)["revenue"].sum()

print(payment_analysis)

retail_df["payment_status"].value_counts()

retail_df.to_csv(
    "cleaned_retail_data.csv",
    index=False
)

print("Dataset Exported Successfully")

import os

print(os.getcwd())
print(os.listdir())

from google.colab import files

files.download("cleaned_retail_data.csv")